name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
            - name: "Install dependencies"
              run: pip install -r requirements.txt
            - name: "Sphinx link check"
              run: sphinx-build docs -W -b linkcheck -d docs/_build/doctrees docs/_build/html
            - name: "Sphinx build"
              run: sphinx-build docs docs/_build
            - name: "Deploy"
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/docs') }}
              with:
                    publish_branch: gh-pages
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: docs/_build/
                    force_orphan: true